# Welcome to Serverless!
#
# For full config options, check out the Alibaba Cloud Function Compute
# plugin docs:
#    https://github.com/aliyun/serverless-aliyun-function-compute
#
# For documentation on Alibaba Cloud Function Compute itself:
#    https://serverless.aliyun.com

# Update the service name below with your own service name

service: image-crawler-python

provider:
  name: aliyun
  region: us-east-1
  runtime: python2.7
  credentials: ~/.aliyuncli/credentials # path must be absolute
  ramRoleStatements:
    - Effect: Allow
      Action:
        - oss:GetObject
        - oss:PutObject
      Resource:
        - '*'

plugins:
  - serverless-aliyun-function-compute
package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  image-crawler:
    handler: index.handler
    events:
      - http:
        path: /crawl
        method: post